### ISSUE TITLE
Can't install editor from ppa:supertux-dev/daily in Ubuntu 16.04

### ISSUE THREAD

**Issue by jbruni** [SuperTux/supertux-editor#2]
I can't install supertux-level-editor using PPA, because `libmono-system-runtime2.0-cil` and `mono-gmcs` are not available in Ubuntu 16.04

I'm following the instructions at http://www.linux.org/threads/super-tux-2-level-editor.8021/

```
sudo add-apt-repository ppa:supertux-dev/daily
sudo apt-get update
sudo apt-get install supertux-editor-git
```

It works in previous Ubuntu, but not in latest... is there a workaround? What can I do?

Thank you.

P.S. - the error message appears in Portuguese in my system... I will copy/paste it below:

> Lendo listas de pacotes... Pronto
> Construindo árvore de dependências  
> Lendo informação de estado... Pronto
> Alguns pacotes não puderam ser instalados. Isto pode significar que
> você solicitou uma situação impossível ou, se você está usando a
> distribuição instável, que alguns pacotes requeridos não foram
> criados ainda ou foram retirados da "Incoming".
> A informação a seguir pode ajudar a resolver a situação:
> 
> Os pacotes a seguir têm dependências desencontradas:
>  supertux-editor-git : Depende: libmono-system-runtime2.0-cil mas não é instalável
>                        Depende: mono-gmcs mas não é instalável
> E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.

**Comment by BlaCoiso** [comment]
The issue there isn't really with Supertux Editor, but with the fact that Mono hasn't been released yet to Ubuntu 16.04, so that's why it worked with a previous version of Ubuntu. The only thing you can do is wait for the Mono Runtime to be released for 16.04 or downgrade Ubuntu. Can you try to run 'sudo apt-get update' and check if there are any errors?

**Comment by maxteufel** [comment]
mono (<http://packages.ubuntu.com/search?keywords=mono&searchon=names&suite=xenial&section=all>) and gtk-sharp-2 seem to be packaged for Ubuntu's xenial release, which are, in addition to SuperTux itself, the only dependencies.

Please note that this PPA is not in any way official or supported, so I'm closing this.

**Comment by BlaCoiso** [comment]
Well, it claims it needs libmono-system-runtime2.0-cil but http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libmono-system-runtime2&searchon=names shows that there isn't any package for xenial, only for precise, trusty and wily. The same happens with mono-gmcs.

**Comment by maxteufel** [comment]
It claims that because the package is old (and not intended for xenial, packages for old Ubuntu releases shouldn't be used on newer releases, it most likely won't work anyway). As a replacement for mono-gmcs, the dmcs compiler works fine for me on Arch Linux.
