### ISSUE TITLE
Tiles menu is really broken

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux-editor#3]
They say a picture is worth 1000 words:
![screenshot - 060516 - 23 06 45](https://cloud.githubusercontent.com/assets/8019640/15087286/831830e0-13df-11e6-8b13-e8ba43fea465.png)
The "glitch art" changes every time I use the editor. It's pretty cool-looking but you can't actually place any tiles.

There are no out-of-ordinary error messages in the console whatsoever.

**Comment by 165your4** [comment]
Oh, I forgot to mention - this is the latest revision of the editor running the latest revision of Supertux.

**Comment by brmbrmcar** [comment]
Can you try putting in an older tiles file? Does trying to create a worldmap work?

**Comment by 165your4** [comment]
Nvm, it fixed itself.
